# Generated by Django 4.0.4 on 2022-08-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_start', models.SmallIntegerField()),
                ('age_end', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('dicofre', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=60)),
                ('county_name', models.CharField(max_length=60)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('population_density', models.IntegerField(blank=True, null=True)),
                ('density_1', models.IntegerField(blank=True, null=True)),
                ('density_2', models.IntegerField(blank=True, null=True)),
                ('density_3', models.IntegerField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('confirmed_new', models.IntegerField(blank=True, null=True)),
                ('confirmed_unknown', models.IntegerField(blank=True, null=True)),
                ('not_confirmed', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('interned', models.IntegerField(blank=True, null=True)),
                ('interned_icu', models.IntegerField(blank=True, null=True)),
                ('interned_infirmary', models.IntegerField(blank=True, null=True)),
                ('lab', models.IntegerField(blank=True, null=True)),
                ('suspects', models.IntegerField(blank=True, null=True)),
                ('vigilance', models.IntegerField(blank=True, null=True)),
                ('transmission_chains', models.IntegerField(blank=True, null=True)),
                ('transmission_imported', models.IntegerField(blank=True, null=True)),
                ('incidence_continent', models.IntegerField(blank=True, null=True)),
                ('incidence_national', models.IntegerField(blank=True, null=True)),
                ('rt_continent', models.IntegerField(blank=True, null=True)),
                ('rt_national', models.IntegerField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'general_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='DATE')),
                ('dicofre', models.IntegerField()),
                ('incidence', models.IntegerField(blank=True, null=True)),
                ('cases_14', models.IntegerField(blank=True, null=True)),
                ('confirmed_1', models.IntegerField(blank=True, null=True)),
                ('confirmed_14', models.IntegerField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'incidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_lower_limit', models.IntegerField()),
                ('category_upper_limit', models.IntegerField(blank=True, null=True)),
                ('incidence_risk', models.IntegerField()),
            ],
            options={
                'db_table': 'incidence_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulationByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicofre', models.SmallIntegerField()),
                ('people', models.IntegerField()),
            ],
            options={
                'db_table': 'population_by_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reinforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('age_id', models.IntegerField()),
                ('reinforcement_qty', models.IntegerField()),
                ('inserted_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'reinforcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('new', models.IntegerField(blank=True, null=True)),
                ('pcr', models.IntegerField(blank=True, null=True)),
                ('pcr_new', models.IntegerField(blank=True, null=True)),
                ('antigen', models.IntegerField(blank=True, null=True)),
                ('antigen_new', models.IntegerField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics_by_age_and_sex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsByRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics_by_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsBySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('confirmed_unknown', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics_by_sex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('number', models.IntegerField(blank=True, db_column='NUMBER', null=True)),
            ],
            options={
                'db_table': 'symptoms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'symptoms_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalDeaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicofre', models.SmallIntegerField()),
                ('week', models.SmallIntegerField()),
                ('week_year', models.SmallIntegerField()),
                ('week_day', models.SmallIntegerField()),
                ('deaths', models.IntegerField()),
                ('inserted_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'total_deaths',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('limit_lower', models.IntegerField(blank=True, null=True)),
                ('limit_upper', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transmission_risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='DATE')),
                ('doses', models.IntegerField(blank=True, null=True)),
                ('doses_new', models.IntegerField(blank=True, null=True)),
                ('doses_1', models.IntegerField(blank=True, null=True)),
                ('doses_1_new', models.IntegerField(blank=True, null=True)),
                ('doses_2', models.IntegerField(blank=True, null=True)),
                ('doses_2_new', models.IntegerField(blank=True, null=True)),
                ('vaccinated_completely', models.IntegerField(blank=True, null=True)),
                ('vaccinated_completely_new', models.IntegerField(blank=True, null=True)),
                ('vaccinated_partially', models.IntegerField(blank=True, null=True)),
                ('vaccinated_partially_new', models.IntegerField(blank=True, null=True)),
                ('inoculated', models.IntegerField(blank=True, null=True)),
                ('inoculated_new', models.IntegerField(blank=True, null=True)),
                ('inoculated_12_more', models.IntegerField(blank=True, null=True)),
                ('vaccines', models.IntegerField(blank=True, null=True)),
                ('vaccines_new', models.IntegerField(blank=True, null=True)),
                ('vaccinated_fully_continent', models.IntegerField(blank=True, null=True)),
                ('vaccinated_fully_continent_new', models.IntegerField(blank=True, null=True)),
                ('reinforcement', models.IntegerField(blank=True, null=True)),
                ('reinforce_new', models.IntegerField(blank=True, null=True)),
                ('reinforcement_continent', models.IntegerField(blank=True, null=True)),
                ('reinforcement_continent_new', models.IntegerField(blank=True, null=True)),
                ('flu', models.IntegerField(blank=True, null=True)),
                ('flu_new', models.IntegerField(blank=True, null=True)),
                ('vaccination_started_05_11', models.IntegerField(blank=True, null=True)),
                ('vaccination_started_05_11_new', models.IntegerField(blank=True, null=True)),
                ('vaccination_complete_05_11', models.IntegerField(blank=True, null=True)),
                ('vaccination_complete_05_11_new', models.IntegerField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'vaccines',
                'managed': False,
            },
        ),
    ]
